export const LIBRARY_GENRE_ID_MAP = Object.freeze({
  1: 'Action',
  2: 'Adventure',
  4: 'Comedy',
  7: 'Mystery',
  8: 'Drama',
  10: 'Fantasy',
  14: 'Horror',
  18: 'Mecha',
  19: 'Music',
  22: 'Romance',
  23: 'School',
  24: 'Sci-Fi',
  27: 'Shounen',
  30: 'Sports',
  36: 'Slice of Life',
  37: 'Supernatural',
  40: 'Psychological',
  41: 'Thriller',
  42: 'Seinen',
});
